### ISSUE TITLE
PowerShell 6

### ISSUE THREAD

**Issue by kensel** [mithrandyr/SimplySql#1]
Have you done any testing or work to make this compatible with PowerShell 6 on linux?  I get the following error when I try to connect initially.
```

PS /> Open-MySqlConnection -ConnectionName some-mysql -Server 127.0.0.1 -UserName root -Password password
Exception calling "Open" with "0" argument(s): "The type initializer for 'MySql.Data.MySqlClient.Replication.ReplicationManager' threw an exception."
At /root/.local/share/powershell/Modules/SimplySql/1.2.0/Providers/MySql/config.ps1:76 char:11
+     Try { $conn.Open() }
+           ~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : TypeInitializationException


```

**Comment by mithrandyr** [comment]
@kensel Sorry for the delay in reply -- no I have not done any testing on PowerShell v6 yet.  As far as I can tell, I would need to release a completely different codebase for the module to work on v6.  Its something I may look into later this year, but not right now.
