### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [mithrandyr/SimplySql#103]
I had a problem with SimplySQL.
My problem was a minor, acceptable one.
(I will open another issue for that problem.)

SimplySql uses the same provider for MySQL/MariaDB.
[`The list of incompatibilities grows longer with each version.` - From Wikipedia](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/)

Thus, need to separate them to support MariaDB correctly I think.

**Comment by mithrandyr** [comment]
@luceat-lux-vestra  -- thank you for sharing this -- I read through the article and the issues seem to be at the database level and not at the connector level.  I.E. that a MySQL provider will work just fine against either MySql or MariaDB.
![image](https://user-images.githubusercontent.com/16905470/204097846-96623f8a-1f5a-4e25-a1bf-412008e13170.png)

SimplySql just wraps a provider and exposes common provider interactions via powershell cmdlets.  So I'm not clear why SimplySql would need a different provider for MariaDB, can you help me to see the where the difference exists at the provider level?

**Comment by luceat-lux-vestra** [comment]
I think you're right.  

It's my fault.

Thanks for your kind reply.
