### ISSUE TITLE
Open connection with connection name doesn't work

### ISSUE THREAD

**Issue by rmjoia** [mithrandyr/SimplySql#113]
When I try to open a connection, at least for PostgreSQL with the parameter `-ConnectionName` doesn't error, but doesn't open the connection, only if I remove it and use the default name.

Also, despite I get the warning to use credentials instead of -UserName and `-Password`, `-Credentials` is not on the Wiki

**Comment by mithrandyr** [comment]
@rmjoia  can you provide an example of what you are trying to do and what the error message is?

**Comment by rmjoia** [comment]
Hi, yeah I got it, the thing is that there's nothing fancy that I'm doing. It's just simple usage.

``` 
            Open-PostGreConnection `
                -Server $hostname `
                -Database $databaseName `
                -Credential ([pscredential]::new($databaseUser, (ConvertTo-SecureString -Force -AsPlainText $PGPassword)))
```

just by using 

```
            Open-PostGreConnection `
                -ConnectionName $connectionName `
                -Server $hostname `
                -Database $databaseName `
                -Credential ([pscredential]::new($databaseUser, (ConvertTo-SecureString -Force -AsPlainText $PGPassword)))          
```

If it helps, the server is in Azure

In this particular case, removing the `-ConnectionName $connectionName` ` was enough to be able to connect, hence why I'm letting you know.

**Comment by mithrandyr** [comment]
@rmjoia  -- the server being in azure should be an issue.  When you say that it doesn't connect when you use the -ConnectionName parameter (of `Open-PostGreConnection`) how do you know?  Do you run either `Show-SqlConnection -ConnectionName $connectionName` or `Show-SqlConnection -All` or `Get-SqlConnection -ConnectionName $connectionName`?

Also are you using WindowsPowershell 5.1 or PowerShell 7?

I'm not able to reproduce this issue, but there is fundamentally no difference in how a connection to Postgre is made, regardless of whether you use -ConnectionName or not.  Actually, when you don't pass in -ConnectionName, then it defaults to "default" -- so the logic of the module is always using a ConnectionName.

Please try passing in "alpha" (hardcoded) for the connection name and then running show-sqlconnection alpha after wards:
```powershell
Open-PostGreConnection -ConnectionName alpha
Show-SqlConnection -ConnectionName alpha
```

**Comment by rmjoia** [comment]
I used `Show-SqlConnection` without the `-All` parameter. Now I tested it again, and indeed, using it, or querying it with the parameter or with the `-ConnectionName` parameter lists it, but when I invoke a query, it returns an error.

![image](https://user-images.githubusercontent.com/7287148/226284674-1e661eaf-f4d1-4ff4-936a-b23015c9daa8.png)

![image](https://user-images.githubusercontent.com/7287148/226285143-3dd9f7bb-210a-4a8f-a568-8d792907b0a4.png)

![image](https://user-images.githubusercontent.com/7287148/226285306-afdd42a5-4b73-4e2c-93d7-bb570d147a11.png)

When I try to query, it doesn't pick the other name, I'm thinking that's because it uses the "default" name? I didn't look into the "code" yet... and apparently, I can't use the `-ConnectionName` parameter with the `Invoke-SqlQuery` command.

![image](https://user-images.githubusercontent.com/7287148/226285745-67bb6e2e-bbcb-4ef9-bd1a-ebd61b0026c7.png)

My powershell version:
![image](https://user-images.githubusercontent.com/7287148/226286118-7696b55c-9f36-4b24-a13b-54d68a25bd30.png)

With alpha is the same, when I try to get the connection without the name or invoke a query, I get the error that no connection was found... only default works. It's no dealbreaker for me, but I just wanted to let you know.

**Comment by rmjoia** [comment]
But, as I also mentioned before and provided screenshot, invoke sqlquery
doesnt accept that parameter... unless i had a typo...

**Comment by mithrandyr** [comment]
Yes - you had a typo -- use used `--ConnectionName` not `-ConnectionName` 
you used 2 dashes instead of 1 dash.

**Comment by rmjoia** [comment]
I'll give it another go tomorrow and I'll let you know. thanks for all the support!

**Comment by rmjoia** [comment]
Sorry @mithrandyr works fine, my bad. 🫣🙄sorry for making you waste your time.
