### ISSUE TITLE
Issue with MariaDB 10.11

### ISSUE THREAD

**Issue by Ruizu22** [mithrandyr/SimplySql#120]
Hi,

It appears that SimplySQL cannot work with MariaDB 10.11. I encounter this error when attempting to open a connection:

Exception occurred when calling 'Open' with '0' argument(s): 'Unable to cast an object of DBNull to other types.'
+     Try { $conn.Open() }
+           ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidCastException
 
I have come across the following information:
- https://stackoverflow.com/questions/74060289/mysqlconnection-open-system-invalidcastexception-object-cannot-be-cast-from-d
- https://bugs.mysql.com/bug.php?id=109331

The issue is caused by a modification in MariaDB, and the MySQL connector will not be updated to work with MariaDB.

Regards

**Comment by ITSNOTSTUPIDIFITWORKS** [comment]
The only solution for SimplySql, that I see, would be the change from MySql.Data to [MySqlConnector](https://mysqlconnector.net/tutorials/migrating-from-connector-net/)´.

@mithrandyr Maybe you have something planned for v2?

**Comment by mameier1234** [comment]
@mithrandyr some news about 2.0 ?

**Comment by mithrandyr** [comment]
@mameier1234  -- finishing up the last set of tests and double-checking I've made all the changes.. had to take a break for some graduate work, but so far my test suite is passing on ubuntu, ps7 and ps5.1 !.

**Comment by mithrandyr** [comment]
@mameier1234  -- V2 is released, please try it out and let me know of any issues you find.
