### ISSUE TITLE
Created a wrapper for SimplySql to allow pipeline input

### ISSUE THREAD

**Issue by gitfvb** [mithrandyr/SimplySql#121]
Hi @mithrandyr and @JediNite,

during the last few weeks I learned to work with SimplySql and it works well for me. To allow easier pipeline input with automatic parameter hashtable creation I have created another module which I am happy to share the code. This is just a side note and you can find it here: https://github.com/Apteco/AptecoPSModules/tree/main/SqlPipeline or just install it via [PSGallery](https://www.powershellgallery.com/packages/SqlPipeline).

Keep up the good work on v2!

Thanks
Florian

**Comment by mithrandyr** [comment]
@gitfvb  -- Thanks, that is really cool!  In version 2 of the module (in progress, delayed b/c of work + school) I added support for pipelining the parameters.. but nothing like this -- so this is really cool and a nice enhancement, even for version 2 when it gets released!

**Comment by gitfvb** [comment]
Sounds good, I wish you all the best for work and school and let me know if I can help you with something. Maybe testing would be a good idea. I am closing this issue now as you are aware :-)
