### ISSUE TITLE
Connection is not opened when using the -ConnectionName parameter of Open-OracleConnection

### ISSUE THREAD

**Issue by mdoyle-cvi** [mithrandyr/SimplySql#125]
as per the title, if I specify a string in the -ConnectionName parameter when using Open-OracleConnection, no connection is created

example:

Open-OracleConnection -DataSource "server" -Port 9011 -ServiceName "database" -Credential $Credential -ErrorAction Stop -ConnectionName "test" 
Get-SqlConnection                                                                                                                    
_WARNING: There is no active SQL Connection._
Test-SqlConnection -ConnectionName "test"
_False_

If I don't specify anything then it works fine

example:

Open-OracleConnection -DataSource "server" -Port 9011 -ServiceName "database" -Credential $Credential -ErrorAction Stop
Get-SqlConnection                                                                                                                    
_ConnectionString    : DATA
                      SOURCE="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=server)(PORT=9011))(CONNECT_DATA=(SERVICE_NAME=database)))";STATEMENT     
                      CACHE SIZE=5
State               : Open_
Test-SqlConnection -ConnectionName "default"
_True_

**Comment by mithrandyr** [comment]
@mdoyle-cvi  -- I can't reproduce your issue.  I'm using the latest released version (1.9) in Windows PowerShell 5.1
```powershell
Open-OracleConnection -DataSource localhost -ServiceName xe -Credential (Get-Credential) -ConnectionName test
Get-SqlConnection test
Show-SqlConnection test
```
those work.. meanwhile, if i don't specify a `-ConnectionName` -- then the default value of "default" will be used and there are no connections of that sort.
```powershell
Show-SqlConnection -All
```

please provide the output of `$PSVersionTable`

**Comment by mdoyle-cvi** [comment]
Also using PowerShell 5.1, and v 1.9.1 of this module. Interestingly, Show-SqlConnection -All does show the "test" connection, but Get-SqlConnection does not. and Close-SqlConnection cannot close it either, and Invoke-SqlQuery can't query it either, very odd.

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by mdoyle-cvi** [comment]
This is working now, not sure why exactly. I uninstalled the SQLServer module since yours supports more than just MSSQLServer and now it is working, so perhaps they were conflicting somehow.

**Comment by mithrandyr** [comment]
Glad that you were able to resolve.
