### ISSUE TITLE
Exception calling "Open" with "0" argument(s): "Object cannot be cast from DBNull to other types."

### ISSUE THREAD

**Issue by computechrr** [mithrandyr/SimplySql#126]
Exception: C:\Program Files\PowerShell\Modules\SimplySql\1.9.1\Providers\MySql\config.ps1:101:11

using powershell 7.4.1 mariadbserver 11.2 on windows server 2019
Open-MySqlConnection -Server '127.0.0.1' -ConnectionName 'localhost' -port '3306' -Database 'server-inventory' -Credential $mysqlcreds
this occurs when running the script the 1st time. if I run it again while it is still open in studio code, it works.

**Comment by mithrandyr** [comment]
@computechrr  -- version 1.9.1 has not been certified for Powershell 7 -- so you might find issues.  Version 2, which is almost complete -- will fully support PowerShell 7 + cross platform.

**Comment by computechrr** [comment]
Thank you, did not realize that 7 wasn’t yet supported.

Thank you

Ted Reichelt
