### ISSUE TITLE
WIKI page text needs an update on username and password part

### ISSUE THREAD

**Issue by tomerikko** [mithrandyr/SimplySql#135]
https://github.com/mithrandyr/SimplySql/wiki/Open-MySqlConnection

and i wish you can consider keeping username\password.   
Credentials might be better, but i am unsure why not to continue giving us the choice to select between the 2.

Though the decision is yours!

**Comment by mithrandyr** [comment]
@tomerikko  -- I've updated the Wiki to redirect to the Docs folder where I actually maintain the documentation now.
