### ISSUE TITLE
Specified cast is not valid

### ISSUE THREAD

**Issue by eilandnl** [mithrandyr/SimplySql#14]
When trying to bulk copy data from oracle to mssql i get the specified cast is not valid, but i can't figure out what field is causing it (i first create the table by doing an select into from openrowsets and the bulk copying it with simplysql) 

Error message: "Conversion failed when converting the nvarchar value 'invoke-sqlbulkcopy : exception calling "writetoserver" with "1" argument(s): "specified cast is not valid."' to data type int."

This is a table that doesnt work (Oracle)
field1 number
field2 number(15,0)
field3 number (15,0) 
field4 number (15,0)
field5 varchar2(10)
field6 number(19,4)
field7 number 
field8 varchar2(10)

And this is the table in mssql
field1 float
field2 numeric(15,0)
field3 numeric(15,0)
field4 numeric(15,0)
field5 nvarchar(10)
field6 numeri(19,4)
field7 float
field8 nvarchar(10)

**Comment by mithrandyr** [comment]
@eilandnl I think you issue may be related to using the openrowsets.  Try copying the data into a local temporary table in Oracle and then doing the bulkcopy from oracle to sql server.

I've tried to recreate the issue, but have not been successful.  If you want me to look further, create and attach .sql files (that will create a table in oracle, create a table in SQL Server and populate the oracle table) -- that reproduce this issue.  FYI -- I tested with oracle 11.2 and with Sql Server 2017 LocalDB
