### ISSUE TITLE
Invoke-SqlUpdate: The argument passed is not serializable. Parameter name: value

### ISSUE THREAD

**Issue by devistar** [mithrandyr/SimplySql#141]
I get this error when I want to perform an insert or update query with or without parameters. However the query works when I do it directly in MariaDB.

**Comment by mithrandyr** [comment]
@devistar  -- I don't see a query listed in your message, can you please update with the query and error and which version of SimplySql you have loaded? -- thanks!

**Comment by devistar** [comment]
The problem is solved. This was because the file that executed the script was not UTF8 BOM encoded. So this caused an error with the accents.
