### ISSUE TITLE
Module fails to import on Server 2016 OS

### ISSUE THREAD

**Issue by jantari** [mithrandyr/SimplySql#16]
Hi, thanks for the great module.

After successfully installing it with:

`Find-Module "SimplySql" | Install-Module -Scope AllUsers -Force`

it fails to import on Server 2016 due to a missing .NET Standard dependency or so I've inferred from this error:

[Imgur](https://i.imgur.com/gDlTkTa.png)

It works on my local machine where I have Visual Studio 2017 installed which presumably included this. From googling it appears one might also be able to resolve this by installing the .NET Core SDK, however that's a little much.

Would it be possible for you to fix this entirely on your side/bundle the dependencies with the Module?

Or is there at least a way you recommend for me to get this working, preferably without installing huge SDKs on a Server.

Thank you

**Comment by mithrandyr** [comment]
@jantari Do you have .net framework 4.6.1 installed on your server?  targeting .net standard shouldn't require .net core. http://immo.landwerth.net/netstandard-versions/#

**Comment by mithrandyr** [comment]
@jantari  -- I've included the necessary shims (additional files) for .net framework 4.6.1 -- I've done some testing, would appreciate you confirming that this is now working on your system.  update to 1.6.2 -- will be on powershellgallery in about 15 minutes.

**Comment by jantari** [comment]
It works out of the box now - this is ideal as Server 2016 is still very widely used 👍 

thank you very much for the quick fix!
