### ISSUE TITLE
Request for adding a new Provider : CSV

### ISSUE THREAD

**Issue by Tonic8** [mithrandyr/SimplySql#17]
Hello

Thanks you for your very usefull module!  :)

It could be interesting to add a new source provider, the CSV allowing the ability to do SQL request on a CSV data. 

i don't know if it's hard to add it but there is a way using Microsoft’s ACE provider, like in this [article](https://www.powershellmagazine.com/2015/05/12/natively-query-csv-files-using-sql-syntax-in-powershell/)

Actually i'm using a script to import a CSV in SQLite db and then use your module to request the SQLlite db.

as i have some db to request and csv file to request : one module to rules them all, etc, etc... :)

Tonic8

**Comment by mithrandyr** [comment]
@Tonic8  -- I've looked through this and the way bulkcopy loading works, it requires that a datareader provide relevant details around the data (namely type information) -- however, I have not found a .net provider to read csv files and provide a full-featured datareader.  That said, with the 2.0 update that is coming, you will be able to pipe objects directly into `Invoke-SqlUpdate` and have the properties of those objects automatically treated as parameter values.  Combine this with transactions, and you will have a pretty effecient means of loading data from CSVs files.  Granted if you are loading millions of rows from csv files, then the performance will not be as good as native approaches.. but for smaller scenarios, this should be quick and easy.

Something like this will be feasible in 2.0
```powershell
Open-SqlConnection -Server "someSqlInstance" -Database "someDatabase"
Start-SqlTransaction
Import-CSV -path "to-some-file.csv" | Invoke-SqlUpdate -Query "INSERT INTO someTable (colA, colB, colC) VALUES (@a, @b, @c)
Complete-SqlTransaction
``
