### ISSUE TITLE
I installed simplysql module but it appears it is missing

### ISSUE THREAD

**Issue by srzelic** [mithrandyr/SimplySql#21]
I installed simplysql module but it appears it is missing. I tried the same on several PCs.
All PCs are PS > 5 , windows 10. Please see verbose logs below.
Any clue?

PS C:\WINDOWS\system32> Install-Module -Name SimplySql -Verbose
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='SimplySql'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'SimplySql'.
VERBOSE: Performing the operation "Install-Module" on target "Version '1.6.2' of module 'SimplySql'".

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'SimplySql' with version '1.6.2' from the repository
'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='SimplySql'' for ''.
VERBOSE: InstallPackage' - name='SimplySql',
version='1.6.2',destination='C:\Users\Win10user\AppData\Local\Temp\2064638562'
VERBOSE: DownloadPackage' - name='SimplySql',
version='1.6.2',destination='C:\Users\Win10user\AppData\Local\Temp\2064638562\SimplySql\SimplySql.nupkg',
uri='https://www.powershellgallery.com/api/v2/package/SimplySql/1.6.2'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/SimplySql/1.6.2'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/SimplySql/1.6.2'.
VERBOSE: Completed downloading 'SimplySql'.
VERBOSE: Hash for package 'SimplySql' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='SimplySql',
version='1.6.2',destination='C:\Users\Win10user\AppData\Local\Temp\2064638562'
VERBOSE: Catalog file 'SimplySql.cat' is not found in the contents of the module 'SimplySql' being installed.
VERBOSE: Module 'SimplySql' was installed successfully to path 'C:\Program
Files\WindowsPowerShell\Modules\SimplySql\1.6.2'.

**Comment by mithrandyr** [comment]
@srzelic -- are there any files in the location 'C:\Program Files\WindowsPowerShell\Modules\SimplySql\1.6.2' ? -- if so.. what happens when you run

```powershell
Import-Module SimplySql -Verbose
Get-Command -Module SimplySql
```

also, check your PSModulePath:
```
$env:PSModulePath -split ";"
```
make sure that 'C:\Program Files\WindowsPowerShell\Modules\' is one of the items listed

**Comment by srzelic** [comment]
Mithrandyr... Everything started working after some time by itself. Not sure what was going on.
i checked get-module, get-command - module simplysql and didn't get any results. I checked  path that you mentioned, all was there but nothing appears. This was really strange for me as I'm using powershell for years. Thank you for you answer.

**Comment by mithrandyr** [comment]
@srzelic Glad that it is working now!
