### ISSUE TITLE
Cmdlet command not recognized

### ISSUE THREAD

**Issue by cetubig** [mithrandyr/SimplySql#26]
Open-MySqlConnection : The term 'Open-MySqlConnection' is not recognized as the name of a cmdlet, function, script

**Comment by mithrandyr** [comment]
Have you imported the module?
run the following and post the output.

```powershell
Import-Module SimplySql -Force
Get-Module SimplySql | Select-Object ModuleType, Version, Name
(Get-Module SimplySql).ExportedCommands.Keys | Where-Object { $_ -like "open*"}
```

**Comment by cetubig** [comment]
Yes, I imported the module many times but no luck.

**Comment by mithrandyr** [comment]
@cetubig Can you run the powershell code that I mentioned above and post the results?
Also, what version of Powershell are you running?

**Comment by mithrandyr** [comment]
@cetubig Also, are you using PowerShell 5.1? 
```powershell
$PSVersionTable
<# returns something like this?
Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
#>
```

Further, there should be errors in the `$error` variable -- so take a look at those errors?
For a clean check, run powershell with the `-noprofile` flag (so nothing loads), then import simplysql, check for errors, then try running a command, check for errors, etc.

**Comment by cetubig** [comment]
Yes I'm using PowerShell 5.1. I'll try next time. I already found working
cmdlet module. Thanks.

**Comment by mithrandyr** [comment]
Not Reproducible.
