### ISSUE TITLE
Wrong words with accents when querying MySQL Database with charset UTF8...

### ISSUE THREAD

**Issue by MarioAlexMartini** [mithrandyr/SimplySql#28]
Source: Script Porwershell

I am querying a information in a MySQL database with charset utf8. When I  use the column data, the words with accents show wrong character, for exemplo, the name Maurício it is show like MaurÃ-cio.

How may I query the correct name from MySQL Database with charset utf8?

**Comment by mithrandyr** [comment]
@MarioAlexMartini  -- sorry for the delay.  This issue may be the fact that windows PowerShell (powershell.exe) on windows doesn't natively support UTF8.  Check this out:
https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell
