### ISSUE TITLE
MSSQL provider

### ISSUE THREAD

**Issue by thorstenkampe** [mithrandyr/SimplySql#30]
The MSSQL provider does not expose parameters for setting `Encrypt` and `TrustServerCertificate` - as opposed to the MySQL and PostgreSQL provider which support encryption.

**Comment by mithrandyr** [comment]
@thorstenkampe  -- I'm actively working on 2.0 (making the module work against .NET standard 2.0 and thus work on both PS 5.1 and PS7) -- as part of this, I'm tackling various QoL and enhancements -- yours will be included.  I'll be adding a new hashtable parameter to each Open-Sql* cmdlet, provide the hashtable will allow adding any additional parameter that a connection string needs that is not already provided by the cmdlet itself.  This will also bridge the gap between using -ConnectionString (and having to build it yourself, just to add in a couple of parameters).

**Comment by mithrandyr** [comment]
Version 2.0 released!

**Comment by computechrr** [comment]
Awesome just in time for my project.  thanks for getting this done!
