### ISSUE TITLE
Closing connection doesn't close database session

### ISSUE THREAD

**Issue by thorstenkampe** [mithrandyr/SimplySql#31]
Closing a database connection doesn't close the session on the database server. Tested with MSSQL, MySQL, Oracle and PostgreSQL. (PowerShell and database servers all latest versions)

**Comment by thorstenkampe** [comment]
Exiting the shell from which the connection was opened, closes the session immediately.

**Comment by mithrandyr** [comment]
@thorstenkampe, is it possible that this is a symptom of connection pooling? You can double check the logic for the [Close-SqlConnecttion ](https://github.com/mithrandyr/SimplySql/blob/master/SimplySql/Cmdlets/Close-SqlConnection.ps1) command.  As you can see, the connection is being Closed and then Disposed...

**Comment by thorstenkampe** [comment]
Yes, I thought so myself. The connections sooner or later will disappear except for Oracle where it seems the connection stays indefinitely. At the moment `Close-SqlConnection` is somehow a no-op - it doesn't do anything tangible from what I can see.

**Comment by mithrandyr** [comment]
@thorstenkampe  -- see this from Oracle: [OracleConnection.Close()](https://docs.oracle.com/database/121/ODPNT/OracleConnectionClass.htm#i1000979).

As far as I can tell, if the connection is remaining open, then the oracle instance has connection pooling and the lifetime has not been exceeded.
