### ISSUE TITLE
Invoke-SqlUpdate fails to read from stream on Postgres Azure PaaS

### ISSUE THREAD

**Issue by twerthi** [mithrandyr/SimplySql#39]
When using SimplySql against an Azure PaaS PostgreSQL server fails when creating a database.  The database does get created, but the command fails with

```
NotSpecified: Exception calling "ExecuteNonQuery" with "0" argument(s): "Exception while reading from stream" 
At /usr/local/share/powershell/Modules/SimplySql/1.7.0/Cmdlets/Invoke-SqlUpdate.ps1:44 char:19 
+             Try { Write-Output $cmd.ExecuteNonQuery() } 
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
at Invoke-SqlUpdate, /usr/local/share/powershell/Modules/SimplySql/1.7.0/Cmdlets/Invoke-SqlUpdate.ps1: line 44 
at <ScriptBlock>, /etc/octopus/Work/20210223230801-288694-57/Script.ps1: line 118 
at <ScriptBlock>, <No file>: line 1 
at <ScriptBlock>, /etc/octopus/Work/20210223230801-288694-57/Octopus.FunctionAppenderContext.ps1: line 185 
at <ScriptBlock>, /etc/octopus/Work/20210223230801-288694-57/Bootstrap.Octopus.FunctionAppenderContext.ps1: line 3057 
at <ScriptBlock>, <No file>: line 1 
at <ScriptBlock>, <No file>: line 1 
```

**Comment by twerthi** [comment]
This same command works fine with Postgresql running in a container, this seems to occur specifically with Posgresql Azure PaaS server.

**Comment by mithrandyr** [comment]
@twerthi  -- Can you post 1) the SQL statement you are executing and 2) the actual line of PowerShell?.  At the moment I don't have an Postgresql Azure PaaS server to test against -- have you tried this command against such a server in the past and it succeeded?  (Trying to identify if the 1.7.0 update introduce a bug or not.)

**Comment by twerthi** [comment]
Here is the line PowerShell with the SQL statement in it
```PowerShell
$executionResult = Invoke-SqlUpdate "CREATE DATABASE `"MyCoolDatabase`";"
```
I've not run this against an Azure PaaS instance of PostgreSQL, just PostgreSQL installed on servers, running in a container, and an AWS RDS instance.  Everything except Azure PaaS works fine.

**Comment by twerthi** [comment]
I just tested against an Azure PaaS MySQL instance and it worked fine so it's specific to PostgreSQL.

**Comment by mithrandyr** [comment]
@twerthi  -- just to make sure that Azure isn't choking on something weird -- can you try with the following command

```powershell
Invoke-SqlUpdate -Query "CREATE DATABASE MyCoolDatabase;"

#if the database name needs to be dynamic -- then try something like this:
$dbName = "MyCoolDatabase"
Invoke-SqlUpdate -Query "CREATE DATABASE $dbName;"
```
Also -- can you explore the error a bit more fully, extract the full exception message (and inner exception message if there is one)?  That might give a clue as to what is going on.

**Comment by twerthi** [comment]
So this is strange ... if the PaaS server has been created recently, it fails.  If it's been up for a while, it works fine.  I have an automated process that spins up and tears down the PaaS server.  It was created several hours ago and I just tried this again without changing anything and it worked fine.  I'll do some more experimentation today.

**Comment by twerthi** [comment]
Perhaps not ... done several tests today and it's inconsistently failing.  It hasn't failed with the `-Query` added, but it has worked the original way.  I'll continue to see if I can find a pattern.

**Comment by mithrandyr** [comment]
@twerthi  -- Whether you have "-Query" or use positional parameters won't matter (the underlying logic of the cmdlet is the same).  What could be the case is the use of quotes inside the command string that is being sent to the server.  However, this seems less likely due to the fact that it works sometimes and fails others.

If you extract the full error (interrogate the `$error` variable), you might find additional details to allow you to troubleshoot what is happening.  Also, check the logs for the instance, that might reveal the problem.

At this point I'm going to close this issue as it doesn't look like a SimplySql problem.  If you find additional evidence to suggest that it is something with SimplySql, please feel free to reopen.

**Comment by twerthi** [comment]
This turned out to be a Timeout issue, adding a command timeout value to let it wait a little longer resolved the issue.
