### ISSUE TITLE
Unable to set ConnectionName

### ISSUE THREAD

**Issue by dmcconnell68** [mithrandyr/SimplySql#42]
If I run this command:
Open-MySqlConnection -Server $x.server -Database $x.database -Credential $x.Credential -ConnectionName "development"
I get no active connections

If I remove the -ConnectionName property it works and the connection name is "default"

Am I missing something?  Sometimes I need to have multiple db connections open at once.  I am assuming that is accomplished by giving each one a unique ConnectionName?

Powershell version 5.1
SimplySQL version 1.7.0

**Comment by mithrandyr** [comment]
@dmcconnell68 SimplySql does allow for multiple connections to be opened at the same time.  All the other commands in the module also have a `-ConnectionName` parameter.  The default value for this is "default".  So when you open a connection without specifying it, it will use "default".  When you query a connection without it, it will use default.

```powershell
# these are equivalent to each other
Open-SqlConnection -SqlServer someServer01 -SqlDatabase someDb
Open-SqlConnection -SqlServer someServer01 -SqlDatabase someDb -ConnectionName default

# these are equivalent to each other as well
Invoke-SqlQuery -Query "SELECT * FROM someTable"
Invoke-SqlQuery -Query "SELECT * FROM someTable" -ConnectionName default

#these are also identical
Close-SqlConnection
Close-SqlConnection -ConnectionName Default #this one will do nothing, since the connection is already closed.

# both of these will fail, "no connection active"
Invoke-SqlQuery -Query "SELECT * FROM someTable" -ConnectionName someOtherConnection
Invoke-SqlQuery -Query "SELECT * FROM someTable" -ConnectionName default

##### Putting it all together
# Reopen a connection
Open-SqlConnection -SqlServer someServer01 -SqlDatabase someDb
#this will fail, no connection exists
Invoke-SqlQuery -Query "SELECT * FROM someTable" -ConnectionName someOtherConnection 
# this will succeed
Invoke-SqlQuery -Query "SELECT * FROM someTable"
#close the connection
Close-SqlConnnection

#Open a new connection
Open-SqlConnection -SqlServer someServer01 -SqlDatabase someDb -ConnectionName someOtherConnection
#this will fail, no connection exists
Invoke-SqlQuery -Query "SELECT * FROM someTable"
# this will succeed
Invoke-SqlQuery -Query "SELECT * FROM someTable" -ConnectionName someOtherConnection 
#close the connection
Close-SqlConnnection -ConnectionName someOtherConnection
```

The point of all the examples is this -- once you use one of the `Open-*Connection` cmdlets with the `-ConnectionName` parameter, you will need to pass that same value to `-ConnectionName` for every other cmdlet that you want to use that connection.

If you still have questions/issues, please post the code with the error messages.  Thanks.

**Comment by dmcconnell68** [comment]
Hi, thanks for the reply.  Your explanation is the way that I assumed this should work.  My problem is with the Open-MySqlConnection command.  If I specify the -ConnectionName parameter, it doesn't open a connection.  You can see below where I ran it on the command line, the first one didn't work, when I removed the -ConnectionName parameter it worked.

**Try #1**
PS D:\scripts\common> Open-MySqlConnection -Server $db_dev.server -Database $db_dev.database -Credential $db_dev.Credentials **-ConnectionName dev**
PS D:\scripts\common> show-sqlconnection
WARNING: There is no active SQL Connection.
PS D:\scripts\common> get-sqlconnection
WARNING: There is no active SQL Connection.

**Try #2**
PS D:\scripts\common>
PS D:\scripts\common> Open-MySqlConnection -Server $db_dev.server -Database $db_dev.database -Credential 
db_dev.Credentials
PS D:\scripts\common> show-sqlconnection

ConnectionName   : default
ProviderType     : MySql
ConnectionState  : Open
ConnectionString : server=dc1wstsxmql01;database=stsportal;port=3306;user
                   id=hidden;useaffectedrows=True;allowuservariables=True;sslmode=None
ServerVersion    : 5.7.20-log
DataSource       : dc1wstsxmql01.res.prod.global
Database         : stsportal
CommandTimeout   : 30
HasTransaction   : False

**Comment by mithrandyr** [comment]
@dmcconnell68 
Please see the WIKI for [Get-SqlConnection](https://github.com/mithrandyr/SimplySql/wiki/Get-SqlConnection) and for [Show-SqlConnection](https://github.com/mithrandyr/SimplySql/wiki/Show-SqlConnection).

You will notice that both of these commands (just like every other cmdlet in the module) has a `-ConnectionName` parameter.  To get the underlying connection object or to show the details around an existing connection, you must specify the `-ConnectionName` parameter.  Every single time you use a cmdlet in the module, you must specify `-ConnectionName` (unless you are using the default connection), otherwise how will the cmdlet know which connection to execute your action against?

```powersherll
# This opens a MySql connection with the connection name 'dev'
Open-MySqlConnection -Server $db_dev.server -Database $db_dev.database -Credential $db_dev.Credentials -ConnectionName dev

# This will attempt to show the connection details for the default connection ('default')
Show-SqlConnection

# This will show the connection details for the connection you actually created
Show-SqlConnection -ConnectionName dev
```
