### ISSUE TITLE
Exception when trying to open MySQL connection

### ISSUE THREAD

**Issue by dragonq1** [mithrandyr/SimplySql#44]
I'm trying to open a connection to MySQL database using the following cmdlet:
`Open-MySqlConnection -Server '(host)'  -Credential $SQLCred -Database '(db name)'`
I have tried the same but with a connection string but both attempts resulted in the following error:

> 
Line |
 100 |      Try { $conn.Open() }
     |            ~~~~~~~~~~~~
     | Exception calling "Open" with "0" argument(s): "Unable to connect to any of the specified MySQL
     | hosts."

Additional information:
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

SimplySQL version: 1.8.0

**Comment by mithrandyr** [comment]
@dragonq1  -- I see that you are using PowerShell 7.  I haven't done any testing of this module with PS7, can you try with PS5.1 and see if you can reproduce.

I also suspect that your value for `-server` is incorrect, are you trying to connect to a mysql server on the local computer?  if so, then I think you should be using `-server localhost`.

**Comment by dragonq1** [comment]
Unfortunately I have no control of PS version on the machine. The server value was just replaced because there was a host name I could not show. But I have been able to solve the problem with some testing. I have replaced the Mysql.Data.dll in the providors directory with the latest version. This seems to have solved the problem and I have no issues with the module now.

**Comment by mithrandyr** [comment]
@dragonq1  -- if the machine is a windows machine, then you can 'Windows Powershell' in order to run 5.1 (they are side-by-side).  Or you can do `Import-Module SimplySql -UseWindowsPowerShell` as that will load the module in a backwards compatible manner.

As I suspected, it was PS7 causing the issues (PS7 is based on .NET Core and I haven't updated the module to fully support running on .NET Core yet -- hopefully this summer)
