### ISSUE TITLE
Invoke-SqlQuery DataTable.DataSet is corrupted for PostGreSQL.

### ISSUE THREAD

**Issue by GitterJu** [mithrandyr/SimplySql#46]
When I run a sql script with multiple queries I recover the last table in a DataTable which belong to a DataSet.
DataSet seems to hold all the dataTable with the results of each query in the sql script twice.
Sadly the Relations is not implemented.

I go around with copying the dataTables in a fresh DataSet but it's bit sad.

**Comment by mithrandyr** [comment]
@GitterJu  -- please provide the code (or a sample of it) that demonstrates this -- then I can see about helping you.

Here is a snippet that might help you understand what is happening.
```powershell
#query with multiple results
$r = Invoke-SqlQuery "select 1 as column1; select 2 as columnA"

#you will notice that the type for the variable 'r' is system.array
$r.GetType()

# you can see that there are 2 objects in this array
$r.count

#lets see what the type is for one of those objects -- its a datatable!
$r[0].gettype()

#you can also see that there is a dataset associated with this datatable
$r[0].dataset

#and it has multiple tables in it
$r[0].dataset.tables.count
```

**Comment by GitterJu** [comment]
Sorry, I should have shared the code. That's my first comment ever.
I'm travelling so I do not have all the exact code on hand but it's pretty simple

I used $r = Invoke-SqlQuery -AsDatatable -Query "select 1 as column1; select 2 as columnA"
(I'll check again when I'll be back home but I really think I got a DataTable and not an Array, thanks to the -AsDatatable switch I assume)
then $ds = $r.DataSet 
At that point I see 4 tables. $ds.Tables.Count get me 4 and I see table table1 table table1 when listing.
The second issue I have is that the $ds.Relations.Add or $ds.Relations.GetType() crashes cause $ds.Relations is null.

Nothing blocking though, I just copy the tables in a newly created DataSet and it works fine but a small bit of doc might saves some time to the next noob.

I'm happy to help if I can but I'm quite a noob on PS.

**Comment by mithrandyr** [comment]
`$ds = $r.DataSet` is the wrong approach.  since `$r` is an array, you just unwrapped the DataSet attribute of each item in that array.  if you have multiple results, the query will return datatables as the output (one for each result), thus giving you an array.
