### ISSUE TITLE
Can't create MySQL stored procedure with Invoke-SqlUpdate

### ISSUE THREAD

**Issue by pcgeek86** [mithrandyr/SimplySql#49]
## Synopsis

I'm trying to use the `Invoke-SqlUpdate` command in the `SimplySql` PowerShell module to create a MySQL Stored Procedure. The query I have authored works perfectly fine when I copy/paste it into Adminer. However, when I try to use SimplySql, the query fails. The following error message is returned by the MySQL database engine.

```
Invoke-SqlUpdate: Exception calling "ExecuteNonQuery" with "0" argument(s): "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER //
CREATE PROCEDURE cbtnuggets.sp_addPerson (IN firstName varchar(30)' at line 1"
```

My suggestion would be to add an extra automated test, to ensure that insertion of stored procedures and functions works correctly. If I can find time to do this, I will submit a pull request to the project.

## Reproduction Steps

```powershell
Invoke-SqlUpdate -Query @'
DELIMITER //

CREATE PROCEDURE cbtnuggets.sp_addPerson (IN firstName varchar(30), IN lastName varchar(30))
  BEGIN
    INSERT INTO cbtnuggets.people (firstName, lastName) VALUES (@firstName, @lastName);
  END//
'@
```

**Comment by pcgeek86** [comment]
Sent a pull request that adds a new test #50

**Comment by mithrandyr** [comment]
@pcgeek86  -- is it possible to create a stored procedure in mySQL using the following:
```powershell
Invoke-SqlUpdate -Query @'
CREATE PROCEDURE cbtnuggets.sp_addPerson (IN firstName varchar(30), IN lastName varchar(30))
  BEGIN
    INSERT INTO cbtnuggets.people (firstName, lastName) VALUES (@firstName, @lastName);
  END
'@
```

i.e. -- is the "DELIMETER //" needed or not?  I'm asking this because sometimes syntax is actually a feature of a tool, rather than the underlying database engine.  "GO" in SQL Server Management Studio (SSMS) is an example of this -- its supported by SSMS and a couple of Microsoft's commandline tools that ship with SSMS.  However "GO" is not part of TSQL syntax and thus the SQL engine doesn't know what to do with it.  I'm wondering if this "DELIMETER //" syntax is similar.

Please try without it and see if the procedure is created successfully or not.

**Comment by pcgeek86** [comment]
@mithrandyr The `DELIMITER` syntax is often necessary for creating complex MySQL objects, especially when using `BEGIN..END` to define a complex function or stored procedure. This is required because the semi-colon is interpreted as a statement terminator inside of the stored procedure's body.

If you try to do it using your syntax, it breaks. Check out the screenshot from Adminer.

![image](https://user-images.githubusercontent.com/466713/130821259-9a062017-040f-42bc-b27e-68a2615e4bd4.png)

As you can see, I have added an automated test in pull request #50.

For further information about the necessity of `DELIMITER //` see this post: https://stackoverflow.com/questions/10259504/delimiters-in-mysql

**Comment by pcgeek86** [comment]
Okay, so I tried your query through the MySQL .NET client, and it seems to work okay. But now I'm confused ... why does your query fail when I try to run it through Adminer (haven't tested phpMyAdmin yet), but it works okay when it runs through the MySQL .NET interface?

**Comment by pcgeek86** [comment]
I reproduced the issue using the MySQL Python connector as well, with the exact same error message, so I stand corrected. I suppose `DELIMITER` isn't necessary when using the MySQL APIs. I am still confused about why this is the case. I thought the whole reason that using `DELIMITER` was necessary, was to instruct the MySQL parser that a semi-colon inside the `BEGIN..END` block should *not* terminate the entire `CREATE PROCEDURE` statement. I'll have to do some more research on that.

Here's a screenshot of the same, original error message I received, using the Python connector.

<img width="840" alt="Screen Shot 2021-08-25 at 10 20 13 AM" src="https://user-images.githubusercontent.com/466713/130827919-e1e3b784-b449-452a-aac2-5cec2b259e9e.png">

**Comment by pcgeek86** [comment]
See this article: https://www.mysqltutorial.org/mysql-stored-procedure/mysql-delimiter/

I'm still confused why using the custom delimiter is not necessary via API.
