### ISSUE TITLE
LastInsertedID after INSERT

### ISSUE THREAD

**Issue by astapelfeld** [mithrandyr/SimplySql#51]
How can I get the Last-Inserted-ID after inserting a row?
Invoke-SQLUpdate returns only an integer (modified rows)
I am using the MySQL Provider

**Comment by mithrandyr** [comment]
@astapelfeld  -- MySql has a function for returning the last inserted ID ([see example](https://www.w3schools.com/Sql/func_mysql_last_insert_id.asp))

So after running your insert statement using `Invoke-SqlUpdate`, then run a query statement using either `Invoke-SqlQuery` or `Invoke-SqlScalar`

```PowerShell
Invoke-SqlUpdate -Query "INSERT INTO someTable (Name) Values ('someName')"
$InsertedId = Invoke-SqlScalar -Query "SELECT LAST_INSERT_ID()"
```
