### ISSUE TITLE
Invoke-SQLBulkCopy from PSObject

### ISSUE THREAD

**Issue by daisy613** [mithrandyr/SimplySql#52]
Cannot Invoke-SQLBulkCopy from a PSObject instead of a source db.

**Comment by mithrandyr** [comment]
This is not yet supported, though is on the wishlist.  I do not have an ETA -- haven't been able to work on new features for the past year, though I've corrected bugs that arise.

**Comment by mithrandyr** [comment]
@daisy613  -- I found a nuget package that will produce a datareader from any Enumerable object -- this should make it easy to support piping (or passing in an array of objects) to **Invoke-SqlBulkCopy** to be loaded.  This is planned to be fixed in 2.0, which I'm actively working on.

**Comment by mithrandyr** [comment]
This has proven to be a bit more complicated than I originally thought (to fully implement the different components of DataReader for PSObjects).  However, I've added the ability to pipe objects to `Invoke-SqlUpdate`, which if combined with transactions, will provide fast loading of data.
