### ISSUE TITLE
Running UPDATE MySQL query using Invoke-SQ

### ISSUE THREAD

**Issue by Fantasy-Fights-TV** [mithrandyr/SimplySql#53]
I am trying to run a MySql update query to update some a single column to a new value and running into issues:

![image](https://user-images.githubusercontent.com/93622511/142651138-57274f86-367b-445d-ae29-1663ceaa6767.png)

Any thoughts here 

*P.S. I have tried quoting the string "Closed" and that did not work either*

**Comment by mithrandyr** [comment]
@Fantasy-Fights-TV  , your hashtable for the parameters is incorrect.  `betStatus` is being set to the command 'Closed'  and not to a string value.. see below

```powershell
#if you run this, it will fail
@{betStatus = Closed}

#if you run this, it will succeed
@{betStatus = "Closed"}
```

**Comment by Fantasy-Fights-TV** [comment]
So I tried that and its still not working:

Invoke-SqlUpdate -Query "UPDATE matchHistory SET betStatus = @betStatus WHERE matchID = @matchID" -Parameters @{betStatus = "Closed"; matchID = $matchID} -ConnectionName FFMySQLDB

![image](https://user-images.githubusercontent.com/93622511/142662958-59e22fda-9541-4c3a-a23a-64f5d75bc685.png)

**Comment by mithrandyr** [comment]
@Fantasy-Fights-TV  -- you will need to explore the error variable and see the full details.  I suspect the 'Fatal error encountered during command execution' is actually coming from the database system and not from Powershell.  In which case, there is something up with either your SQL statement or the database.
