### ISSUE TITLE
Add ability to prepare a query

### ISSUE THREAD

**Issue by realslacker** [mithrandyr/SimplySql#56]
Sometimes it is useful to see how a query will look without actually executing it. I would love to see the ability to prepare a query integrated.

In my mind this could be accomplished on Invoke-* by adding SupportsShouldProcess and making -WhatIf dump out the query to the console.

It looks from the code that this should work, but it doesn't so I'm probably missing something...

```PowerShell
$SimplySql = Import-Module SimplySql -PassThru

$SqlConnectionParams = @{
    Server          = 'server'
    Database        = 'database'
    Credential      = [pscredential]::new( 'read_only', ( ConvertTo-SecureString -String 'read_only' -AsPlainText -Force ) )
}

Open-MySqlConnection @SqlConnectionParams -ConnectionName 'Test'

$Command = & $SimplySql { $Script:Connections.Test.GetCommand( 'SELECT @Test', 30, @{ Test = 'Hello World' } ) }
$Command.Prepare()
```

**Comment by mithrandyr** [comment]
@realslacker See the [SqlServer implementation of ADO.Net](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.prepare?view=netframework-4.8).  The method does not return any output.  What exactly are you expecting to see when ".Prepare()" is called?  The module does not touch the queries that you pass in, it executes them as is.

**Comment by realslacker** [comment]
I was hoping for a merge of the query and parameters so that I could see the query as it would be executed. Looking over the documentation I'm not sure it's even possible to intercept the prepared query, but I'm not familiar enough with ADO.Net to know.

**Comment by mithrandyr** [comment]
@realslacker  -- Prepare does different things in different providers.  So in something like SQLite, I believe it is a no-op.  On SqlServer or PostgreSQL --- it will tell the database engine to prepare the query, which means to build the execution plan of the query.  Typically, SQL Server (not sure with other engines) generates the execution plan for a query when it is run.  That execute plan can differ depending on the parameter values that are sent, etc.  By preparing a query, you are telling SQL Server to go ahead and generate the plan... and then to keep using that pre-generated plan for execute subsequent execution.  So this can be useful in some batch loading scenarios... where you have a given complex query that you are running multiple times for different parameter values.  You prepare (get the engine to generate the execution plan once) then execute the query multiple times, using different parameter values each time.

All of that to say -- if you are wanting to see the query with a replacement of parameters with values--- .Prepare() will not do that.  I would also caution that a query with hardcoded values can generate a different execution plan than a query with parameter values.  The results will be the same -- but the way the engine gets the results could be different, one plan could be more or less efficient than the other (i.e. take longer or shorter amount of time, or consume less memory/cpu, etc).
