### ISSUE TITLE
close-sqlconnection doesnt close it on server

### ISSUE THREAD

**Issue by EvgeniyShell** [mithrandyr/SimplySql#59]
Hello.
i think close-sqlconnection doesnt close connection on server, sleep status shows. Im using mariadb. its ok? good that script do not dublicate conections like many scripts in php.

**Comment by mithrandyr** [comment]
@EvgeniyShell  -- the `Close-SqlConnection` cmdlet will call the .Close() function on the underlying .NET connection object.  In the case -- [MySqlConnection.Close](https://dev.mysql.com/doc/dev/connector-net/8.0/api/data_api/MySql.Data.MySqlClient.MySqlConnection.html#MySql_Data_MySqlClient_MySqlConnection_Close).

**Comment by EvgeniyShell** [comment]
thank you.
I think its NET bug or something else (may be done specially ), i've noticed, that when you use a function with open and close connection in infinite loop, connection doesnt disappeared, but when you close the script, connection dissapears in database process list.

**Comment by mithrandyr** [comment]
@EvgeniyShell  that may be the effect of connection pooling.  The .NET MySql Provider leverages connection pooling automatically.
