### ISSUE TITLE
MySQL failing on $ds.fill($da) "The given key was not present in the dictionary" when MySQL in a container.

### ISSUE THREAD

**Issue by twerthi** [mithrandyr/SimplySql#60]
When executing against MySQL in a container (version 8), SimplySql is failing on the `Invoke-SqlQuery` command is failing on `$ds.fill($da)` method with the error "The given key was not present in the dictionary".  I attempted to debug, but wasn't able to find out much more than this.

**Comment by mithrandyr** [comment]
@twerthi  -- am I right to assume that both Powershell and MySQL were running in a container?  What version of Powershell was used?  There are some known issues with using the module on PS6+  (it was originally developed/tested against PS5.1 and hasn't been updated to fully support PS 6+).

**Comment by twerthi** [comment]
@mithrandyr -- No, PowerShell was being run from my local machine against a container on a completely separate machine.  Here is the result of `$host.Version` from my local machine

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  613

**Comment by mithrandyr** [comment]
@twerthi  -- ok, so when using the SimplySql to connect to a MySQL instance that is NOT in a container, it works.  but when the MySQL instance is hosted in a container, it fails?

**Comment by twerthi** [comment]
@mithrandyr -- Correct!  I have a MySQL instance on a Windows VM and it works perfectly fine with that as well as AWS, Azure, and GCP.  However, when running as a Linux container, it fails.

**Comment by mithrandyr** [comment]
@twerthi  -- try the `Invoke-SqlScalar` function (as that doesn't use the DataAdapater.Fill) --- that will tell us if the connection itself is good.

you can also use the `Get-SqlConnection` to return the underlying .Net objection for the connection.  Which you can then use to do some additional testing (using the object directly and using .NET).

**Comment by twerthi** [comment]
`Invoke-SqlScalar` fails with the same error message.  Here are the results of `Get-SqlConnection`
```
ServerThread      : 68
DataSource        : docker1
ConnectionTimeout : 15
Database          : 
UseCompression    : False
State             : Open
ServerVersion     : 8.0.29
ConnectionString  : server=docker1;port=3306;user id=root;sslmode=Required
IsPasswordExpired : False
Site              : 
Container         : 
```

I'm not seeing anything out of the ordinary.  I'm attempting to get whether a database exists

```
function Get-DatabaseExists
{
	# Define parameters
    param ($DatabaseName)
    
	# Execute query
    #return Invoke-SqlQuery "SHOW DATABASES LIKE '$DatabaseName';"
    return Invoke-SqlScalar "SHOW DATABASES LIKE '$DatabaseName';"
}

# Create credential object for the connection
$createDatabaseName = "shawntest"
$createPort = 3306
$createUsername = "root"
$createUserPassword = "MyGreatPassword!"
$createMySQLServerName = "docker1"
$createUseSSL = "True"


	# Connect to MySQL
    $connectionString = "Server=$createMySQLServerName;Port=$createPort;Uid=$createUsername;Pwd=$createUserPassword;"
    if ($createUseSSL -eq "True")
    {
		# Append to connection string
        $connectionString += "SslMode=Required;"
    }
    else
    {
    	# Disable ssl
        $connectionString += "SslMode=none;"
    }

    #$connectionString += "sslmode=preferred;"
    
    Open-MySqlConnection -ConnectionString $connectionString

    # See if database exists
    $databaseExists = Get-DatabaseExists -DatabaseName $createDatabaseName

```

**Comment by mithrandyr** [comment]
does it fail during the `Open-MySqlConnection` call or during the `Invoke-SqlScalar` call? -- i.e. are you able to run the code for creating the connection string and calling `Open-MySqlConnection` successfully?

if so -- then you should be able to run the command `Set-SqlConnection -DatabaseName "somename"` and change the database.  I would also run this simple test `Invoke-SqlScalar -query "Select 1"` and see if it executes.. this will tell us if there is something wrong with the module or with your SQL syntax.

Also.. `Invoke-SqlScalar` and `Invoke-SqlQuery` all work with SQL... not necessarily with provider specific commands.  For instance, you can't use "GO" (often used in TSQL Scripts on Sql Server) with the underlying SqlClient .NET classes. -- so its possible that your "SHOW DATABASES..." command is like that (and from my quick googling it seems that this is the case).  You can instead use an actual SQL query "SELECT schema_name FROM information_schema.schemata" that might accomplish something similar.

**Comment by twerthi** [comment]
`Open-MySqlConnection` works successfully, it's only the Invoke-* commands that seem to be failing.  I tried the `Select 1` and that seemed to work OK, the `SELECT schema_name...` one did not.  The part that is confusing is that `SHOW DATABASES` works fine when it's not a container.

**Comment by mithrandyr** [comment]
@twerthi -- if it works fine outside a container, but fails inside a container, then I suspect that there is something different with the instance of MySQL inside the container than your instances of MySQL outside the container.  You might also explore standard MySQL tools for accessing a database, have them connect to the container instance and try running the "SHOW Database" command.

**Comment by twerthi** [comment]
I agree, just can't figure out what the difference is.  I can tell you that a create database statement works fine, but the selects seem to be failing.  I thought it might have something to do with character sets, but both seem to be using the same one.  I've got MySQL workbench, but I'm not experienced enough with MySQL to determine where to go from here.

**Comment by twerthi** [comment]
Digging a little more, this could be related to this - https://stackoverflow.com/questions/68645324/system-notsupportedexception-character-set-utf8mb3-is-not-supported-by-net-f which would necessitate an upgrade for the mysql.data.dll.  I've a PR which updates this for a different reason, but perhaps this could be what's going on?

**Comment by mithrandyr** [comment]
could be -- did you try altering the character set?  I am wanting to get upgraded versions of the connectors included -- but also wanting to get PS7 compatibility -- which is taking more time than I wanted.  Part of the problem is that later connector packages have dependencies on other nuget packages.. and PowerShell doesn't have the great system for handling this.  I.e. if package Acme.dll was compiled against OtherStuff.dll (v1.0.0.0) -- then theoretically you can also run Acme.dll with OtherStuff.dll (v1.0.01).  However, Powershell doesn't do version redirects natively -- and while there are ways to handle this... each approach is complex and has tradeoffs.  Anyways, I would try the charset change -- otherwise, I'm hoping to have time this summer to finish the PS7 compatibility improvements, which also will include later versions of all connectors.

**Comment by twerthi** [comment]
@mithrandyr I tested my PR version, it fixes the issue.  My PR updates the MySQL.data.dll as well as includes the dependencies required (I know what you mean, it was a bit of a pain to get it right).

**Comment by twerthi** [comment]
Is there something wrong with the PR?  I'd be happy to fix it if there is :)

**Comment by mithrandyr** [comment]
@twerthi  -- I just haven't had the time to explore the PR -- I will try and look this weekend, but I'm in the midst of end of semester work and probably won't have time for another week.

**Comment by mithrandyr** [comment]
@twerthi I've updated (v1.9.0) -- can you confirm that this has been resolved?  Thanks for your assistance.
