### ISSUE TITLE
Upgrading to MySQL 8.29 breaks Powershell Module.

### ISSUE THREAD

**Issue by DHorneDBA** [mithrandyr/SimplySql#62]
Immediately after upgrading the DB engine to MySQL 8.29, the simplysql throws this error:
Exception calling "Fill" with "1" argument(s): "Character set 'utf8mb3' is not supported by .Net Framework."
At C:\Program Files\WindowsPowerShell\Modules\SimplySql\Providers\MySql\provider.ps1:42 char:13
+             $da.Fill($ds)
+             ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException

It looks like simplysql is using an older version of the .NET driver. How do I point it to the updated version of the driver? We have to run 8.0.29 for compliance reasons.

**Comment by mithrandyr** [comment]
@DHorneDBA  -- this should be fixed in version 1.9.0 -- @twerthi also reported this and provided the work to upgrade the DLL used.  Please try and let us know if you still have issues.

**Comment by DHorneDBA** [comment]
Yes the update resolved the issue. Thanks!
