### ISSUE TITLE
FIPS

### ISSUE THREAD

**Issue by Squid-Bomb** [mithrandyr/SimplySql#65]
When trying to connect to a Postgres DB I get the following error.  "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."  The system I am on needs to stay FIPS compliant.

**Comment by mithrandyr** [comment]
@Squid-Bomb  -- I can't make any guarantees that the module is FIPS compliant.  I suspect this may be a problem with the version of NPGSQL I'm using (it's an older version, hasn't been updated yet).  If you can determine if any version of NPGSQL is FIPS compliant and provide that information here, that would be helpful in providing a potential solution.

**Comment by mithrandyr** [comment]
The assumption that this will be fixed in 2.0 is based on the upgrade version of NPGSQL that will be utilized.

**Comment by mithrandyr** [comment]
Version 2.0 released!
