### ISSUE TITLE
Issue with postgres/rds proxy.

### ISSUE THREAD

**Issue by HatBeardZero** [mithrandyr/SimplySql#66]
I get the below error when I try to connect to a rds postgres server via aws rds proxy.  It works directly, but the proxy errors on it.  

"Open" with "0" argument(s): "0A000: Feature not supported: RDS Proxy currently doesn’t support the option ssl_renegotiation_limit."

I replaced the Npgsql.dll with the 6.0.5.0 version and it works fine from what I can tell.

**Comment by mithrandyr** [comment]
Version 2.0 released!
