### ISSUE TITLE
Invoke-SqlQuery Chinese is not supported

### ISSUE THREAD

**Issue by Wangwang2021** [mithrandyr/SimplySql#67]
$data = Invoke-SqlQuery -query "SELECT * FROM someTable WHERE someCol = @var" -Parameters @{var = '你好'}
The above query statement cannot query the data

**Comment by mithrandyr** [comment]
@Wangwang2021  -- the module does not do any manipulation of variables -- it sends them directly to the sql server via parameter bindings.  I would suggest querying that column via the module and storing the value in a PS variable and comparing to what you are passing in.  Something like this:

```powershell
$val = Invoke-SqlScalar -query "SELECT someCol FROM someTable WHERE someID = 1"
$testVal = '' # the Chinese characters

# test to see if they are the same
$val -eq $testval
```

**Comment by Wangwang2021** [comment]
> @Wangwang2021 -- the module does not do any manipulation of variables -- it sends them directly to the sql server via parameter bindings. I would suggest querying that column via the module and storing the value in a PS variable and comparing to what you are passing in. Something like this:
> 
> ```powershell
> $val = Invoke-SqlScalar -query "SELECT someCol FROM someTable WHERE someID = 1"
> $testVal = '' # the Chinese characters
> 
> # test to see if they are the same
> $val -eq $testval
> ```

thank 。Can you support querying directly based on Chinese parameters in the Sql statement?

**Comment by mithrandyr** [comment]
@Wangwang2021 , as I mentioned -- There is nothing in the module (that I'm aware of) that would prevent the use of Chinese characters.  The test I suggested above, should allow you to do some kind of comparison.  I.e. if your powershell environment is not using the same culture as your database column, then that might cause an issue?
