### ISSUE TITLE
Add support for MySqlBulkLoader

### ISSUE THREAD

**Issue by mithrandyr** [mithrandyr/SimplySql#7]
https://dev.mysql.com/doc/connector-net/en/connector-net-programming-bulk-loader.html
This supports bulk loading from a file.

Consider Adding a Connection level attribute (use alternative-loading) and then in Invoke-SqlBulkCopy
write out the information to disk, then process the file into MySQL.

**Comment by daisy613** [comment]
Has this ever been implemented? I would love to be able to bulk insert from an object or a file, instead of individual inserts.

**Comment by mithrandyr** [comment]
This has not been built yet.  However, this is focused on a particular optimization for the MySql database.  There is also a desire to provide functionality that would allow piping objects to `Invoke-SqlBulkCopy` and use those objects as a source, rather than another database connection.

**Comment by mithrandyr** [comment]
This has been implemented in version 2.0 -- working on testing before releasing.
