### ISSUE TITLE
@Wangwang2021  -- the module does not do any manipulation of variables -- it sends them directly to the sql server via parameter bindings.  I would suggest querying that column via the module and storing the value in a PS variable and comparing to what you are passing in.  Something like this:

### ISSUE THREAD

**Issue by Wangwang2021** [mithrandyr/SimplySql#70]
@Wangwang2021  -- the module does not do any manipulation of variables -- it sends them directly to the sql server via parameter bindings.  I would suggest querying that column via the module and storing the value in a PS variable and comparing to what you are passing in.  Something like this:

```powershell
$val = Invoke-SqlScalar -query "SELECT someCol FROM someTable WHERE someID = 1"
$testVal = '' # the Chinese characters

# test to see if they are the same
$val -eq $testval
```

_Originally posted by @mithrandyr in https://github.com/mithrandyr/SimplySql/issues/67#issuecomment-1219516839_

**Comment by Wangwang2021** [comment]
> @Wangwang2021 -- the module does not do any manipulation of variables -- it sends them directly to the sql server via parameter bindings. I would suggest querying that column via the module and storing the value in a PS variable and comparing to what you are passing in. Something like this:
> 
> ```powershell
> $val = Invoke-SqlScalar -query "SELECT someCol FROM someTable WHERE someID = 1"
> $testVal = '' # the Chinese characters
> 
> # test to see if they are the same
> $val -eq $testval
> ```
> 
> _Originally posted by @mithrandyr in [#67 (comment)](https://github.com/mithrandyr/SimplySql/issues/67#issuecomment-1219516839)_

**Comment by mithrandyr** [comment]
This was duplicated from a response to a previous issue.
