### ISSUE TITLE
Invoke-SqlQuery with parameter used multiple times in query

### ISSUE THREAD

**Issue by Ture2019** [mithrandyr/SimplySql#72]
My query refers the same parameter in several places. Does not seem to work today. Query return with empty result. Workaround is obviously to replace parameters inbeforehand. But this is quite a basic feature, would be nice to see fixed. :-)

**Comment by mithrandyr** [comment]
@Ture2019  without an example of what is going wrong (i.e. steps to reproduce) then I cannot provide a fix.  Please provide an example, along with the result you are seeing and then the result you would expect to see.

**Comment by mithrandyr** [comment]
Here is an example of using the parameter in multiple locations in the query -- I'm using the SQLite provider (but it would work with any other providers).

```powershell
Open-SQLiteConnection #this will open an inmemory database
Invoke-SqlQuery "Select @name AS First, @name AS Second, @age AS Third, @name AS Fourth" -Parameters @{name = "John Doe"; age = 50}
Close-SqlConnection
```

**Output:**
```
First    Second   Third Fourth
-----    ------   ----- ------
John Doe John Doe    50 John Doe
```

**Comment by Ture2019** [comment]
Sorry, I can provide a propper example becuase this would involve to set up a test mysql-database. 
But here is my query:
```
SELECT * 
FROM Settlement 
WHERE settlementDate >= @dato 
AND settlementDate < date_add(@dato, INTERVAL 1 DAY)
```

**Comment by mithrandyr** [comment]
@Ture2019  -- so the full powershell code you would be invoking is something like:
```powershell
Open-MySqlConnection -Server $someServer -Database $someDatabase

$query = "SELECT * FROM Settlement WHERE settlementData >= @dato AND settlementDate < date_add(@dato, INTERVAL 1 DAY)"

Invoke-SqlQuery -query $query -parameters @{dato = [datetime]"2022-11-14"}
```

And you are saying that this does not return any results?

**Comment by mithrandyr** [comment]
@Ture2019  -- closing out this issue as I can't reproduce it -- if you can create repro steps, happy to reopen and look into it.
