### ISSUE TITLE
What is the param ConnectionString in Open-OracleConnection

### ISSUE THREAD

**Issue by DarylAndDaryl** [mithrandyr/SimplySql#73]
I am looking to use the Open-OracleConnection.  Can someone explain the ConnectionString parameter and perhaps, provide examples.

**Comment by mithrandyr** [comment]
@DarylAndDaryl  -- the `-ConnectionString` parameter exists to allow the user to provide the exact connection string they want to use.  Providers can have incredibly complicated connection strings and options that can be used to shape the nature of the connection you are creating.  The parameters I offer are simply the most common ones, but if you need something special, then you would need to construct the connection string yourself and pass it to the command.

[Here is a link to example connection strings for Oracle](https://www.connectionstrings.com/oracle/).
