### ISSUE TITLE
Implement SQLite Provider

### ISSUE THREAD

**Issue by mithrandyr** [mithrandyr/SimplySql#79]

**Comment by JediNite** [comment]
@mithrandyr ,

Is there any chance of updating the versions of the dlls for SQLite that are bundled in with SimplySQL ?  I would like to use some of the new features of SQLite and have found these do not work right with the version bundled in 1.9.0.

As a workaround, I manually copied the required dlls from https://system.data.sqlite.org/blobs/1.0.117.0/sqlite-netFx46-static-binary-x64-2015-1.0.117.0.zip and https://system.data.sqlite.org/blobs/1.0.117.0/sqlite-netFx46-static-binary-Win32-2015-1.0.117.0.zip into the locations in associated folders the 1.9.0 release of SimplySQL and this seemed to work okay.

I can see from the "Issues" listed that you are looking to do a re-write, but any chance this can be done in the interim ?

Thanks,

JediNite

**Comment by mithrandyr** [comment]
@JediNite  -- I'm about 60% of the way through reimplementation, I hope to have it finished in the next month.

If you want to create a PR with the updated DLLs, I'm willing to take a look at release an interim version until I can get 2.0 completed.

**Comment by JediNite** [comment]
@mithrandyr,

Pull request raised : https://github.com/mithrandyr/SimplySql/pull/107

Cheers,

JediNite

**Comment by mithrandyr** [comment]
Yes -- I need to do some initial testing and verify that everything looks good, then I'll release.
